// <auto-generated/>
using Lexis.Client.Api.Blogs.Author.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Lexis.Client.Api.Blogs.Author
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Blogs\author
    /// </summary>
    public class AuthorRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the lexis.Client.api.Blogs.author.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="Lexis.Client.Api.Blogs.Author.Item.WithAuthorItemRequestBuilder"/></returns>
        public Lexis.Client.Api.Blogs.Author.Item.WithAuthorItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("authorId", position);
                return new Lexis.Client.Api.Blogs.Author.Item.WithAuthorItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="Lexis.Client.Api.Blogs.Author.AuthorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Blogs/author", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="Lexis.Client.Api.Blogs.Author.AuthorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthorRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Blogs/author", rawUrl)
        {
        }
    }
}
